### ISSUE TITLE
Kakaotalk subscription

### ISSUE THREAD

**Issue by jayhjkwon** [jayhjkwon/korean-food-delivery#13]
## TODO

- [x] Create Kakao channel
- [x] Create CTA button to connect the kakao channel in homepage
- [ ] Send kakao message to the friends when
  - New posting uploaded
  - Posting is updated

## Reference
- 나무위키 about 카카오톡 채널 https://namu.wiki/w/%EC%B9%B4%EC%B9%B4%EC%98%A4%ED%86%A1%EC%B1%84%EB%84%90
- 카카오톡 채널 만들기
https://business.kakao.com/info/kakaotalkchannel/
- 카카오톡 메시지 API
https://developers.kakao.com/docs/latest/ko/message/common
