### ISSUE TITLE
[WIP] [EPIC] Customer can register their post

### ISSUE THREAD

**Issue by jayhjkwon** [jayhjkwon/korean-food-delivery#42]
## Workflow

- Customer authentication
  - AWS Cognito

- Customer sign in 

- Enter data and upload images

- These data will be uploaded to AWS S3 as JSON files in the specific directory

- K-FOOD runs build a few times in Github Actions

- This build will generate static files from the AWS S3 then deploy to Netlify (or just merge into master and it will be automatically deployed to prod by Netlify)

#### Backend
- [ ] 

#### UI
- [ ] A customer can sign up
- [ ] A customer can sign in
- [ ] A customer can upload a post
- [ ] A customer can update a post
- [ ] A customer can delete a post
